### ISSUE TITLE
Text Field is not formatted properly

### ISSUE THREAD

**Issue by ggedde** [timlogemann/code-acf-snippets#1]
there is an issue next to the parent:
Looks like it is missing comma and not using the same parent params as the rest.

![image](https://user-images.githubusercontent.com/3236909/52604336-536c9680-2e1f-11e9-9287-5584161ec685.png)

**Comment by timlogemann** [comment]
Thanks! Have been noticing this myself for a while, but couldn't bother to fix it.
I'll be releasing an update which addresses both of your created issues.
